---
driver:
  name: proxy
  host: localhost
  reset_command: "if(Test-Path $env:ChocolateyInstall) { del $env:ChocolateyInstall -Recurse -Force }"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2

suites:
  - name: chef_12
    provisioner:
      require_chef_omnibus: 12.19.36
    run_list:
      - recipe[chocolatey::default]
    attributes:
      chocolatey:
        install_vars:
          chocolateyVersion: 0.10.5

  - name: chef_latest
    run_list:
      - recipe[chocolatey::default]
    attributes:
      chocolatey:
        install_vars:
          chocolateyVersion: 0.10.5
